// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { locales } from "../../config";
import Header from "./components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

export const metadata = {
    title: "NEXT.JS - INTERNATIONALIZATION",
    description: `Next.js enables you to configure the routing and rendering of
    content to support multiple languages. Making your site adaptive to
    different locales includes translated content (localization) and
    internationalized routes.`
}

export async function generateStaticParams() {
    return locales.map((locale) => ({ lang: locale}));
}

export default async function LocaleLayout({ children, params }) {
    const { lang } = await params;
    return (
        <html lang={lang}>
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/gh/tamanchichan/cdn/reset.css"
                    media="all"
                />
            </head>
            <body>
                <header>
                    <Header params={params}></Header>
                </header>
                <main>
                    {children}
                </main>
                <footer></footer>
            </body>
        </html>
    )
}